### ISSUE TITLE
Next js 14 Modal Import Issue

### ISSUE THREAD

**Issue by coder-aminul** [rizzui/rizzui#66]
**This error is coming when I am going to import and use the modal component in the next js project. How can it be solved?**

`Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `De`.`

![error](https://github.com/rizzui/rizzui/assets/34531732/641e87c8-f37e-4156-ba6f-1aa50cfde71b)

**Comment by ablause** [comment]
I have the same issue, do you have a temporary solution ?

**Comment by idris95** [comment]
hi, everyone!

This issue is due to @headlessui/react v2, which we don't support yet. We're working on an update that will fix this. In the meantime, please use @headlessui/react v1.7.19.

**Comment by idris95** [comment]
Hi, the issue has been resolved in **RizzUI** version **0.8.5**. Please upgrade your **@headlessui/react** and **@floating-ui/react** with the following command:

`npm i @headlessui/react@2.0.3 @floating-ui/react@0.26.13`

**Comment by PiotrKarpinski** [comment]
Hi!
Having the same problem but with Select component.
Tried downgrading to 0.8.5 but it's still broken.

![Image](https://github.com/user-attachments/assets/306998db-21a3-4d06-99e8-ce8aa47236e8)
